<a href="https://colab.research.google.com/github/legong-beep/MPM_204_Gong/blob/main/Shan_Leia%20proposal_cat_CKD_just_ran_glm_interprete_next.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

####Data explore

In [1]:
if(!require(readxl)) install.packages("readxl")
library(readxl)

Loading required package: readxl

In [4]:
cat_df <- read_excel("/content/Chronic_kidney_disease_cats_risk.xlsx")

Warning message:
“Coercing boolean to numeric in AR2 / R2C44”
Warning message:
“Coercing boolean to numeric in AR3 / R3C44”
Warning message:
“Coercing boolean to numeric in AR4 / R4C44”
Warning message:
“Coercing boolean to numeric in AR5 / R5C44”
Warning message:
“Coercing boolean to numeric in AR6 / R6C44”
Warning message:
“Coercing boolean to numeric in AR7 / R7C44”
Warning message:
“Coercing boolean to numeric in AR8 / R8C44”
Warning message:
“Coercing boolean to numeric in AR9 / R9C44”
Warning message:
“Coercing boolean to numeric in AR10 / R10C44”
Warning message:
“Coercing boolean to numeric in AR11 / R11C44”
Warning message:
“Coercing boolean to numeric in AR12 / R12C44”
Warning message:
“Coercing boolean to numeric in AR13 / R13C44”
Warning message:
“Coercing boolean to numeric in AR14 / R14C44”
Warning message:
“Coercing boolean to numeric in AR15 / R15C44”
Warning message:
“Coercing boolean to numeric in AR16 / R16C44”
Warning message:
“Coercing boolean to numeric in AR17 / R17C44”
Warning message:
“Coercing boolean to numeric in AR18 / R18C44”
Warning message:
“Coercing boolean to numeric in AR19 / R19C44”
Warning message:
“Coercing boolean to numeric in AR20 / R20C44”
Warning message:
“Coercing boolean to numeric in AR21 / R21C44”
Warning message:
“Coercing boolean to numeric in AR22 / R22C44”
Warning message:
“Coercing boolean to numeric in AR23 / R23C44”
Warning message:
“Coercing boolean to numeric in AR24 / R24C44”
Warning message:
“Coercing boolean to numeric in AR25 / R25C44”
Warning message:
“Coercing boolean to numeric in AR26 / R26C44”
Warning message:
“Coercing boolean to numeric in AR27 / R27C44”
Warning message:
“Coercing boolean to numeric in AR28 / R28C44”
Warning message:
“Coercing boolean to numeric in AR29 / R29C44”
Warning message:
“Coercing boolean to numeric in AR30 / R30C44”
Warning message:
“Coercing boolean to numeric in AR31 / R31C44”
Warning message:
“Coercing boolean to numeric in AR32 / R32C44”
Warning message:
“Coercing boolean to numeric in AR33 / R33C44”
Warning message:
“Coercing boolean to numeric in AR34 / R34C44”
Warning message:
“Coercing boolean to numeric in AR35 / R35C44”
Warning message:
“Coercing boolean to numeric in AR36 / R36C44”
Warning message:
“Coercing boolean to numeric in AR37 / R37C44”
Warning message:
“Coercing boolean to numeric in AR38 / R38C44”
Warning message:
“Coercing boolean to numeric in AR39 / R39C44”
Warning message:
“Coercing boolean to numeric in AR40 / R40C44”
Warning message:
“Coercing boolean to numeric in AR41 / R41C44”
Warning message:
“Coercing boolean to numeric in AR42 / R42C44”
Warning message:
“Coercing boolean to numeric in AR43 / R43C44”
Warning message:
“Coercing boolean to numeric in AR44 / R44C44”
Warning message:
“Coercing boolean to numeric in AR45 / R45C44”
Warning message:
“Coercing boolean to numeric in AR46 / R46C44”
Warning message:
“Coercing boolean to numeric in AR47 / R47C44”
Warning message:
“Coercing boolean to numeric in AR48 / R48C44”
Warning message:
“Coercing boolean to numeric in AR49 / R49C44”
Warning message:
“Coercing boolean to numeric in AR50 / R50C44”
Warning message:
“Coercing boolean to numeric in AR51 / R51C44”
Warning message:
“Coercing boolean to numeric in AR52 / R52C44”
Warning message:
“Coercing boolean to numeric in AR53 / R53C44”
Warning message:
“Coercing boolean to numeric in AR54 / R54C44”
Warning message:
“Coercing boolean to numeric in AR55 / R55C44”
Warning message:
“Coercing boolean to numeric in AR56 / R56C44”
Warning message:
“Coercing boolean to numeric in AR57 / R57C44”
Warning message:
“Coercing boolean to numeric in AR58 / R58C44”
Warning message:
“Coercing boolean to numeric in AR59 / R59C44”
Warning message:
“Coercing boolean to numeric in AR60 / R60C44”
Warning message:
“Coercing boolean to numeric in AR61 / R61C44”
Warning message:
“Coercing boolean to numeric in AR62 / R62C44”
Warning message:
“Coercing boolean to numeric in AR63 / R63C44”
Warning message:
“Coercing boolean to numeric in AR64 / R64C44”
Warning message:
“Coercing boolean to numeric in AR65 / R65C44”
Warning message:
“Coercing boolean to numeric in AR66 / R66C44”
Warning message:
“Coercing boolean to numeric in AR67 / R67C44”
Warning message:
“Coercing boolean to numeric in AR68 / R68C44”
Warning message:
“Coercing boolean to numeric in AR69 / R69C44”
Warning message:
“Coercing boolean to numeric in AR70 / R70C44”
Warning message:
“Coercing boolean to numeric in AR71 / R71C44”
Warning message:
“Coercing boolean to numeric in AR72 / R72C44”
Warning message:
“Coercing boolean to numeric in AR73 / R73C44”
Warning message:
“Coercing boolean to numeric in AR74 / R74C44”
Warning message:
“Coercing boolean to numeric in AR75 / R75C44”
Warning message:
“Coercing boolean to numeric in AR76 / R76C44”
Warning message:
“Coercing boolean to numeric in AR77 / R77C44”
Warning message:
“Coercing boolean to numeric in AR78 / R78C44”
Warning message:
“Coercing boolean to numeric in AR79 / R79C44”
Warning message:
“Coercing boolean to numeric in AR80 / R80C44”
Warning message:
“Coercing boolean to numeric in AR81 / R81C44”
Warning message:
“Coercing boolean to numeric in AR82 / R82C44”
Warning message:
“Coercing boolean to numeric in AR83 / R83C44”
Warning message:
“Coercing boolean to numeric in AR84 / R84C44”
Warning message:
“Coercing boolean to numeric in AR85 / R85C44”
Warning message:
“Coercing boolean to numeric in AR86 / R86C44”
Warning message:
“Coercing boolean to numeric in AR87 / R87C44”
Warning message:
“Coercing boolean to numeric in AR88 / R88C44”
Warning message:
“Coercing boolean to numeric in AR89 / R89C44”
Warning message:
“Coercing boolean to numeric in AR90 / R90C44”
Warning message:
“Coercing boolean to numeric in AR91 / R91C44”
Warning message:
“Coercing boolean to numeric in AR92 / R92C44”
Warning message:
“Coercing boolean to numeric in AR93 / R93C44”
Warning message:
“Coercing boolean to numeric in AR94 / R94C44”
Warning message:
“Coercing boolean to numeric in AR95 / R95C44”
Warning message:
“Coercing boolean to numeric in AR96 / R96C44”
Warning message:
“Coercing boolean to numeric in AR97 / R97C44”
Warning message:
“Coercing boolean to numeric in AR98 / R98C44”
Warning message:
“Coercing boolean to numeric in AR99 / R99C44”
Warning message:
“Coercing boolean to numeric in AR100 / R100C44”
Warning message:
“Coercing boolean to numeric in AR101 / R101C44”
Warning message:
“Coercing boolean to numeric in AR102 / R102C44”
Warning message:
“Coercing boolean to numeric in AR103 / R103C44”
Warning message:
“Coercing boolean to numeric in AR104 / R104C44”
Warning message:
“Coercing boolean to numeric in AR105 / R105C44”
Warning message:
“Coercing boolean to numeric in AR106 / R106C44”
Warning message:
“Coercing boolean to numeric in AR107 / R107C44”
Warning message:
“Coercing boolean to numeric in AR108 / R108C44”
Warning message:
“Coercing boolean to numeric in AR109 / R109C44”
Warning message:
“Coercing boolean to numeric in AR110 / R110C44”
Warning message:
“Coercing boolean to numeric in AR111 / R111C44”
Warning message:
“Coercing boolean to numeric in AR112 / R112C44”
Warning message:
“Coercing boolean to numeric in AR113 / R113C44”
Warning message:
“Coercing boolean to numeric in AR114 / R114C44”
Warning message:
“Coercing boolean to numeric in AR115 / R115C44”
Warning message:
“Coercing boolean to numeric in AR116 / R116C44”
Warning message:
“Coercing boolean to numeric in AR117 / R117C44”
Warning message:
“Coercing boolean to numeric in AR118 / R118C44”
Warning message:
“Coercing boolean to numeric in AR119 / R119C44”
Warning message:
“Coercing boolean to numeric in AR120 / R120C44”
Warning message:
“Coercing boolean to numeric in AR121 / R121C44”
Warning message:
“Coercing boolean to numeric in AR122 / R122C44”
Warning message:
“Coercing boolean to numeric in AR123 / R123C44”
Warning message:
“Coercing boolean to numeric in AR124 / R124C44”
Warning message:
“Coercing boolean to numeric in AR125 / R125C44”
Warning message:
“Coercing boolean to numeric in AR126 / R126C44”
Warning message:
“Coercing boolean to numeric in AR127 / R127C44”
Warning message:
“Coercing boolean to numeric in AR128 / R128C44”
Warning message:
“Coercing boolean to numeric in AR129 / R129C44”
Warning message:
“Coercing boolean to numeric in AR130 / R130C44”
Warning message:
“Coercing boolean to numeric in AR131 / R131C44”
Warning message:
“Coercing boolean to numeric in AR132 / R132C44”
Warning message:
“Coercing boolean to numeric in AR133 / R133C44”
Warning message:
“Coercing boolean to numeric in AR134 / R134C44”
Warning message:
“Coercing boolean to numeric in AR135 / R135C44”
Warning message:
“Coercing boolean to numeric in AR136 / R136C44”
Warning message:
“Coercing boolean to numeric in AR137 / R137C44”
Warning message:
“Coercing boolean to numeric in AR138 / R138C44”
Warning message:
“Coercing boolean to numeric in AR139 / R139C44”
Warning message:
“Coercing boolean to numeric in AR140 / R140C44”
Warning message:
“Coercing boolean to numeric in AR141 / R141C44”
Warning message:
“Coercing boolean to numeric in AR142 / R142C44”
Warning message:
“Coercing boolean to numeric in AR143 / R143C44”
Warning message:
“Coercing boolean to numeric in AR144 / R144C44”
Warning message:
“Coercing boolean to numeric in AR145 / R145C44”
Warning message:
“Coercing boolean to numeric in AR146 / R146C44”
Warning message:
“Coercing boolean to numeric in AR147 / R147C44”
Warning message:
“Coercing boolean to numeric in AR148 / R148C44”
Warning message:
“Coercing boolean to numeric in AR149 / R149C44”
Warning message:
“Coercing boolean to numeric in AR150 / R150C44”
Warning message:
“Coercing boolean to numeric in AR151 / R151C44”
Warning message:
“Coercing boolean to numeric in AR152 / R152C44”
Warning message:
“Coercing boolean to numeric in AR153 / R153C44”
Warning message:
“Coercing boolean to numeric in AR154 / R154C44”
Warning message:
“Coercing boolean to numeric in AR155 / R155C44”
Warning message:
“Coercing boolean to numeric in AR156 / R156C44”
Warning message:
“Coercing boolean to numeric in AR157 / R157C44”
Warning message:
“Coercing boolean to numeric in AR158 / R158C44”
Warning message:
“Coercing boolean to numeric in AR159 / R159C44”
Warning message:
“Coercing boolean to numeric in AR160 / R160C44”
Warning message:
“Coercing boolean to numeric in AR161 / R161C44”
Warning message:
“Coercing boolean to numeric in AR162 / R162C44”
Warning message:
“Coercing boolean to numeric in AR163 / R163C44”
Warning message:
“Coercing boolean to numeric in AR164 / R164C44”
Warning message:
“Coercing boolean to numeric in AR165 / R165C44”
Warning message:
“Coercing boolean to numeric in AR166 / R166C44”
Warning message:
“Coercing boolean to numeric in AR167 / R167C44”
Warning message:
“Coercing boolean to numeric in AR168 / R168C44”
Warning message:
“Coercing boolean to numeric in AR169 / R169C44”
Warning message:
“Coercing boolean to numeric in AR170 / R170C44”
Warning message:
“Coercing boolean to numeric in AR171 / R171C44”
Warning message:
“Coercing boolean to numeric in AR172 / R172C44”
Warning message:
“Coercing boolean to numeric in AR173 / R173C44”
Warning message:
“Coercing boolean to numeric in AR174 / R174C44”
Warning message:
“Coercing boolean to numeric in AR175 / R175C44”
Warning message:
“Coercing boolean to numeric in AR176 / R176C44”
Warning message:
“Coercing boolean to numeric in AR177 / R177C44”
Warning message:
“Coercing boolean to numeric in AR178 / R178C44”
Warning message:
“Coercing boolean to numeric in AR179 / R179C44”
Warning message:
“Coercing boolean to numeric in AR180 / R180C44”
Warning message:
“Coercing boolean to numeric in AR181 / R181C44”
Warning message:
“Coercing boolean to numeric in AR182 / R182C44”
Warning message:
“Coercing boolean to numeric in AR183 / R183C44”
Warning message:
“Coercing boolean to numeric in AR184 / R184C44”
Warning message:
“Coercing boolean to numeric in AR185 / R185C44”
Warning message:
“Coercing boolean to numeric in AR186 / R186C44”
Warning message:
“Coercing boolean to numeric in AR187 / R187C44”
Warning message:
“Coercing boolean to numeric in AR188 / R188C44”
Warning message:
“Coercing boolean to numeric in AR189 / R189C44”
Warning message:
“Coercing boolean to numeric in AR190 / R190C44”
Warning message:
“Coercing boolean to numeric in AR191 / R191C44”
Warning message:
“Coercing boolean to numeric in AR192 / R192C44”
Warning message:
“Coercing boolean to numeric in AR193 / R193C44”
Warning message:
“Coercing boolean to numeric in AR194 / R194C44”
Warning message:
“Coercing boolean to numeric in AR195 / R195C44”
Warning message:
“Coercing boolean to numeric in AR196 / R196C44”
Warning message:
“Coercing boolean to numeric in AR197 / R197C44”
Warning message:
“Coercing boolean to numeric in AR198 / R198C44”
Warning message:
“Coercing boolean to numeric in AR199 / R199C44”
Warning message:
“Coercing boolean to numeric in AR200 / R200C44”
Warning message:
“Coercing boolean to numeric in AR201 / R201C44”
Warning message:
“Coercing boolean to numeric in AR202 / R202C44”
Warning message:
“Coercing boolean to numeric in AR203 / R203C44”
Warning message:
“Coercing boolean to numeric in AR204 / R204C44”
Warning message:
“Coercing boolean to numeric in AR205 / R205C44”
Warning message:
“Coercing boolean to numeric in AR206 / R206C44”
Warning message:
“Coercing boolean to numeric in AR207 / R207C44”
Warning message:
“Coercing boolean to numeric in AR208 / R208C44”
Warning message:
“Coercing boolean to numeric in AR209 / R209C44”
Warning message:
“Coercing boolean to numeric in AR210 / R210C44”
Warning message:
“Coercing boolean to numeric in AR211 / R211C44”
Warning message:
“Coercing boolean to numeric in AR212 / R212C44”
Warning message:
“Coercing boolean to numeric in AR213 / R213C44”
Warning message:
“Coercing boolean to numeric in AR214 / R214C44”
Warning message:
“Coercing boolean to numeric in AR215 / R215C44”
Warning message:
“Coercing boolean to numeric in AR216 / R216C44”
Warning message:
“Coercing boolean to numeric in AR217 / R217C44”
Warning message:
“Coercing boolean to numeric in AR218 / R218C44”
Warning message:
“Coercing boolean to numeric in AR219 / R219C44”
Warning message:
“Coercing boolean to numeric in AR220 / R220C44”
Warning message:
“Coercing boolean to numeric in AR221 / R221C44”
Warning message:
“Coercing boolean to numeric in AR222 / R222C44”
Warning message:
“Coercing boolean to numeric in AR223 / R223C44”
Warning message:
“Coercing boolean to numeric in AR224 / R224C44”
Warning message:
“Coercing boolean to numeric in AR225 / R225C44”
Warning message:
“Coercing boolean to numeric in AR226 / R226C44”
Warning message:
“Coercing boolean to numeric in AR227 / R227C44”
Warning message:
“Coercing boolean to numeric in AR228 / R228C44”
Warning message:
“Coercing boolean to numeric in AR229 / R229C44”
Warning message:
“Coercing boolean to numeric in AR230 / R230C44”
Warning message:
“Coercing boolean to numeric in AR231 / R231C44”
Warning message:
“Coercing boolean to numeric in AR232 / R232C44”
Warning message:
“Coercing boolean to numeric in AR233 / R233C44”
Warning message:
“Coercing boolean to numeric in AR234 / R234C44”
Warning message:
“Coercing boolean to numeric in AR235 / R235C44”
Warning message:
“Coercing boolean to numeric in AR236 / R236C44”
Warning message:
“Coercing boolean to numeric in AR237 / R237C44”
Warning message:
“Coercing boolean to numeric in AR238 / R238C44”
Warning message:
“Coercing boolean to numeric in AR239 / R239C44”
Warning message:
“Coercing boolean to numeric in AR240 / R240C44”
Warning message:
“Coercing boolean to numeric in AR241 / R241C44”
Warning message:
“Coercing boolean to numeric in AR242 / R242C44”
Warning message:
“Coercing boolean to numeric in AR243 / R243C44”
Warning message:
“Coercing boolean to numeric in AR244 / R244C44”
Warning message:
“Coercing boolean to numeric in AR245 / R245C44”
Warning message:
“Coercing boolean to numeric in AR246 / R246C44”
Warning message:
“Coercing boolean to numeric in AR247 / R247C44”
Warning message:
“Coercing boolean to numeric in AR248 / R248C44”
Warning message:
“Coercing boolean to numeric in AR249 / R249C44”
Warning message:
“Coercing boolean to numeric in AR250 / R250C44”
Warning message:
“Coercing boolean to numeric in AR251 / R251C44”
Warning message:
“Coercing boolean to numeric in AR252 / R252C44”
Warning message:
“Coercing boolean to numeric in AR253 / R253C44”
Warning message:
“Coercing boolean to numeric in AR254 / R254C44”
Warning message:
“Coercing boolean to numeric in AR255 / R255C44”
Warning message:
“Coercing boolean to numeric in AR256 / R256C44”
Warning message:
“Coercing boolean to numeric in AR257 / R257C44”
Warning message:
“Coercing boolean to numeric in AR258 / R258C44”
Warning message:
“Coercing boolean to numeric in AR259 / R259C44”
Warning message:
“Coercing boolean to numeric in AR260 / R260C44”
Warning message:
“Coercing boolean to numeric in AR261 / R261C44”
Warning message:
“Coercing boolean to numeric in AR262 / R262C44”
Warning message:
“Coercing boolean to numeric in AR263 / R263C44”
Warning message:
“Coercing boolean to numeric in AR264 / R264C44”
Warning message:
“Coercing boolean to numeric in AR265 / R265C44”
Warning message:
“Coercing boolean to numeric in AR266 / R266C44”
Warning message:
“Coercing boolean to numeric in AR267 / R267C44”
Warning message:
“Coercing boolean to numeric in AR268 / R268C44”
Warning message:
“Coercing boolean to numeric in AR269 / R269C44”
Warning message:
“Coercing boolean to numeric in AR270 / R270C44”
Warning message:
“Coercing boolean to numeric in AR271 / R271C44”
Warning message:
“Coercing boolean to numeric in AR272 / R272C44”
Warning message:
“Coercing boolean to numeric in AR273 / R273C44”
Warning message:
“Coercing boolean to numeric in AR274 / R274C44”
Warning message:
“Coercing boolean to numeric in AR275 / R275C44”
Warning message:
“Coercing boolean to numeric in AR276 / R276C44”
Warning message:
“Coercing boolean to numeric in AR277 / R277C44”
Warning message:
“Coercing boolean to numeric in AR278 / R278C44”
Warning message:
“Coercing boolean to numeric in AR279 / R279C44”
Warning message:
“Coercing boolean to numeric in AR280 / R280C44”
Warning message:
“Coercing boolean to numeric in AR281 / R281C44”
Warning message:
“Coercing boolean to numeric in AR282 / R282C44”
Warning message:
“Coercing boolean to numeric in AR283 / R283C44”
Warning message:
“Coercing boolean to numeric in AR284 / R284C44”
Warning message:
“Coercing boolean to numeric in AR285 / R285C44”
Warning message:
“Coercing boolean to numeric in AR286 / R286C44”
Warning message:
“Coercing boolean to numeric in AR287 / R287C44”
Warning message:
“Coercing boolean to numeric in AR288 / R288C44”
Warning message:
“Coercing boolean to numeric in AR289 / R289C44”
Warning message:
“Coercing boolean to numeric in AR290 / R290C44”
Warning message:
“Coercing boolean to numeric in AR291 / R291C44”
Warning message:
“Coercing boolean to numeric in AR292 / R292C44”
Warning message:
“Coercing boolean to numeric in AR293 / R293C44”
Warning message:
“Coercing boolean to numeric in AR294 / R294C44”
Warning message:
“Coercing boolean to numeric in AR295 / R295C44”
Warning message:
“Coercing boolean to numeric in AR296 / R296C44”
Warning message:
“Coercing boolean to numeric in AR297 / R297C44”
Warning message:
“Coercing boolean to numeric in AR298 / R298C44”
Warning message:
“Coercing boolean to numeric in AR299 / R299C44”
Warning message:
“Coercing boolean to numeric in AR300 / R300C44”
Warning message:
“Coercing boolean to numeric in AR301 / R301C44”
Warning message:
“Coercing boolean to numeric in AR302 / R302C44”
Warning message:
“Coercing boolean to numeric in AR303 / R303C44”
Warning message:
“Coercing boolean to numeric in AR304 / R304C44”
Warning message:
“Coercing boolean to numeric in AR305 / R305C44”
Warning message:
“Coercing boolean to numeric in AR306 / R306C44”
Warning message:
“Coercing boolean to numeric in AR307 / R307C44”

In [5]:
# 1. first and last 6 rows
head(cat_df)
tail(cat_df)

  ID Breed      Age Sex    Neuter   Case Date of diagnosis
1 1  Crossbreed ?9  Female Neutered Case 2013-02-05
2 2  Purebreed  ?9  Male   NA       Case 2012-03-19
3 3  Crossbreed ?9  Male   Neutered Case 2012-01-30
4 4  Crossbreed ?9  Female Neutered Case 2012-06-19
5 5  Crossbreed ?9  Male   NA       Case 2012-05-10
6 6  Crossbreed ?9  Female NA       Case 2012-01-12
  Reason for presentation BCS at diagnosis (1-9) Last recorded BCS (1-9) ⋯
1 Other                   NA                     NA                      ⋯
2 Not recorded            NA                     NA                      ⋯
3 Clinical signs          NA                     NA                      ⋯
4 Other                   NA                     NA                      ⋯
5 Other                   NA                     NA                      ⋯
6 Geriatric Health clinic NA                     NA                      ⋯
  Retinopathy Cat bite abscess Polycystic kidney disease Pyelonephritis
1 FALSE       FALSE            FALSE                     FALSE
2 FALSE       FALSE            FALSE                     FALSE
3 FALSE       FALSE            FALSE                     FALSE
4 FALSE       FALSE            FALSE                     FALSE
5 FALSE       FALSE            FALSE                     FALSE
6 FALSE       FALSE            FALSE                     FALSE
  hepatopathy obesity constipation Diabetes Mellitus Primary Aldosteronism
1 FALSE       FALSE   FALSE        FALSE             FALSE
2 FALSE       FALSE   FALSE         TRUE             FALSE
3 FALSE       FALSE    TRUE        FALSE             FALSE
4 FALSE       FALSE   FALSE        FALSE             FALSE
5 FALSE       FALSE   FALSE        FALSE             FALSE
6 FALSE       FALSE   FALSE        FALSE             FALSE
  Urethral obstruction
1 0
2 0
3 0
4 0
5 0
6 0

  ID   Breed      Age Sex    Neuter   Case    Date of diagnosis
1 1245 Crossbreed ?9  Female Neutered Control <NA>
2 1246 Crossbreed ?9  Female Neutered Control <NA>
3 1247 Crossbreed ?9  Female Neutered Control <NA>
4 1248 Crossbreed ?9  Male   Neutered Control <NA>
5 1249 Crossbreed ?9  Male   Entire   Control <NA>
6 1250 Crossbreed ?9  Female Entire   Control <NA>
  Reason for presentation BCS at diagnosis (1-9) Last recorded BCS (1-9) ⋯
1 NA                      NA                     NA                      ⋯
2 NA                      NA                     NA                      ⋯
3 NA                      NA                     NA                      ⋯
4 NA                      NA                     NA                      ⋯
5 NA                      NA                     NA                      ⋯
6 NA                      NA                     NA                      ⋯
  Retinopathy Cat bite abscess Polycystic kidney disease Pyelonephritis
1 FALSE       FALSE            FALSE                     FALSE
2 FALSE       FALSE            FALSE                     FALSE
3 FALSE       FALSE            FALSE                     FALSE
4 FALSE        TRUE            FALSE                     FALSE
5 FALSE        TRUE            FALSE                     FALSE
6 FALSE       FALSE            FALSE                     FALSE
  hepatopathy obesity constipation Diabetes Mellitus Primary Aldosteronism
1 FALSE       FALSE   FALSE        FALSE             FALSE
2 FALSE       FALSE   FALSE        FALSE             FALSE
3 FALSE       FALSE   FALSE        FALSE             FALSE
4 FALSE       FALSE   FALSE        FALSE             FALSE
5 FALSE       FALSE   FALSE        FALSE             FALSE
6 FALSE       FALSE   FALSE        FALSE             FALSE
  Urethral obstruction
1 0
2 0
3 0
4 0
5 0
6 0

In [6]:
# 2. rows and columns
dim(cat_df)

[1] 1250   44

In [7]:
# 3. all columns
colnames(cat_df)

 [1] "ID"
 [2] "Breed"
 [3] "Age"
 [4] "Sex"
 [5] "Neuter"
 [6] "Case"
 [7] "Date of diagnosis"
 [8] "Reason for presentation"
 [9] "BCS at diagnosis (1-9)"
[10] "Last recorded BCS (1-9)"
[11] "Heart Murmur"
[12] "HM first recorded"
[13] "Grade of heart murmur"
[14] "Gallop rhythm"
[15] "Date first detected...15"
[16] "Arrhythmia"
[17] "Date first detected...17"
[18] "Goitre"
[19] "Vaccination"
[20] "Previous exposure to nephrotoxic drugs"
[21] "NSAID treatment"
[22] "Date of last exposure to drug"
[23] "Previous anaesthetic"
[24] "Date of last anaesthetic"
[25] "FeLV status"
[26] "FIV status"
[27] "Previous exposure to lilies"
[28] "Previous exposure to ethylene glycol"
[29] "Previous AKI"
[30] "Hyperthyroidism"
[31] "Periodontal disease"
[32] "Arthritis"
[33] "Cystitis/FLUTD"
[34] "Cardiomyopathy"
[35] "Retinopathy"
[36] "Cat bite abscess"
[37] "Polycystic kidney disease"
[38] "Pyelonephritis"
[39] "hepatopathy"
[40] "obesity"
[41] "constipation"
[42] "Diabetes Mellitus"
[43] "Primary Aldosteronism"
[44] "Urethral obstruction"

In [8]:
# 4. data structure
str(cat_df)

tibble [1,250 × 44] (S3: tbl_df/tbl/data.frame)
 $ ID                                    : num [1:1250] 1 2 3 4 5 6 7 8 9 10 ...
 $ Breed                                 : chr [1:1250] "Crossbreed" "Purebreed" "Crossbreed" "Crossbreed" ...
 $ Age                                   : chr [1:1250] "?9" "?9" "?9" "?9" ...
 $ Sex                                   : chr [1:1250] "Female" "Male" "Male" "Female" ...
 $ Neuter                                : chr [1:1250] "Neutered" NA "Neutered" "Neutered" ...
 $ Case                                  : chr [1:1250] "Case" "Case" "Case" "Case" ...
 $ Date of diagnosis                     : POSIXct[1:1250], format: "2013-02-05" "2012-03-19" ...
 $ Reason for presentation               : chr [1:1250] "Other" "Not recorded" "Clinical signs" "Other" ...
 $ BCS at diagnosis (1-9)                : num [1:1250] NA NA NA NA NA NA NA NA NA NA ...
 $ Last recorded BCS (1-9)               : num [1:1250] NA NA NA NA NA NA NA NA NA NA ...
 $ Heart Murmur                          : chr [1:1250] "FALSE" "FALSE" "TRUE" "TRUE" ...
 $ HM first recorded                     : POSIXct[1:1250], format: NA NA ...
 $ Grade of heart murmur                 : num [1:1250] NA NA 5 3 1 NA NA NA NA NA ...
 $ Gallop rhythm                         : chr [1:1250] "FALSE" "FALSE" "FALSE" "TRUE" ...
 $ Date first detected...15              : POSIXct[1:1250], format: NA NA ...
 $ Arrhythmia                            : chr [1:1250] "FALSE" "FALSE" "FALSE" "FALSE" ...
 $ Date first detected...17              : POSIXct[1:1250], format: NA NA ...
 $ Goitre                                : chr [1:1250] "Not recorded" "Not recorded" "FALSE" "FALSE" ...
 $ Vaccination                           : chr [1:1250] "Regular" "None recorded" "None recorded" "Regular" ...
 $ Previous exposure to nephrotoxic drugs: chr [1:1250] "None recorded" "None recorded" "NSAID" "NSAID" ...
 $ NSAID treatment                       : chr [1:1250] NA NA "Repeated one off treatment" "Long term treatment" ...
 $ Date of last exposure to drug         : POSIXct[1:1250], format: NA NA ...
 $ Previous anaesthetic                  : chr [1:1250] "None recorded" "None recorded" "None recorded" "None recorded" ...
 $ Date of last anaesthetic              : POSIXct[1:1250], format: NA NA ...
 $ FeLV status                           : chr [1:1250] "Not tested" "Not tested" "Not tested" "Not tested" ...
 $ FIV status                            : chr [1:1250] "Not tested" "Not tested" "Not tested" "Not tested" ...
 $ Previous exposure to lilies           : chr [1:1250] "None recorded" "None recorded" "None recorded" "None recorded" ...
 $ Previous exposure to ethylene glycol  : chr [1:1250] "None recorded" "None recorded" "None recorded" "None recorded" ...
 $ Previous AKI                          : chr [1:1250] "None recorded" "None recorded" "None recorded" "None recorded" ...
 $ Hyperthyroidism                       : logi [1:1250] TRUE FALSE FALSE FALSE TRUE FALSE ...
 $ Periodontal disease                   : logi [1:1250] FALSE TRUE TRUE TRUE TRUE FALSE ...
 $ Arthritis                             : logi [1:1250] FALSE FALSE FALSE TRUE FALSE FALSE ...
 $ Cystitis/FLUTD                        : logi [1:1250] FALSE FALSE TRUE TRUE FALSE FALSE ...
 $ Cardiomyopathy                        : logi [1:1250] FALSE FALSE FALSE TRUE FALSE FALSE ...
 $ Retinopathy                           : logi [1:1250] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ Cat bite abscess                      : logi [1:1250] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ Polycystic kidney disease             : logi [1:1250] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ Pyelonephritis                        : logi [1:1250] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ hepatopathy                           : logi [1:1250] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ obesity                               : logi [1:1250] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ constipation                          : logi [1:1250] FALSE FALSE TRUE FALSE FALSE FALSE ...
 $ Diabetes Mellitus                     : logi [1:1250] FALSE TRUE FALSE FALSE FALSE FALSE ...
 $ Primary Aldosteronism                 : logi [1:1250] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ Urethral obstruction                  : num [1:1250] 0 0 0 0 0 0 0 0 0 0 ...

In [9]:
# mean median range
summary(cat_df)

       ID               Breed             Age              Sex
 Min.   :   1.0   Length   :1250   Length   :1250   Length   :1250
 1st Qu.: 313.2   N.unique :   3   N.unique :   2   N.unique :   2
 Median : 625.5   N.blank  :   0   N.blank  :   0   N.blank  :   0
 Mean   : 625.5   Min.nchar:   7   Min.nchar:   2   Min.nchar:   4
 3rd Qu.: 937.8   Max.nchar:  10   Max.nchar:   2   Max.nchar:   6
 Max.   :1250.0                    NAs      :  16   NAs      :   7

       Neuter            Case      Date of diagnosis
 Length   :1250   Length   :1250   Min.   :2012-01-03 00:00:00
 N.unique :   2   N.unique :   2   1st Qu.:2012-05-31 00:00:00
 N.blank  :   0   N.blank  :   0   Median :2012-11-21 00:00:00
 Min.nchar:   6   Min.nchar:   4   Mean   :2012-12-03 05:50:12
 Max.nchar:   8   Max.nchar:   7   3rd Qu.:2013-05-20 00:00:00
 NAs      : 349                    Max.   :2013-12-30 00:00:00
                                   NAs    :625
 Reason for presentation BCS at diagnosis (1-9) Last recorded BCS (1-9)
 Length   :1250          Min.   :2.0            Min.   :1.00
 N.unique :   5          1st Qu.:3.0            1st Qu.:2.75
 N.blank  :   0          Median :3.0            Median :3.00
 Min.nchar:   5          Mean   :3.8            Mean   :3.30
 Max.nchar:  23          3rd Qu.:4.0            3rd Qu.:4.00
 NAs      : 625          Max.   :9.0            Max.   :5.00
                         NAs    :1200           NAs    :1230
    Heart Murmur  HM first recorded             Grade of heart murmur
 Length   :1250   Min.   :2007-07-26 00:00:00   Min.   :1.000
 N.unique :   3   1st Qu.:2012-01-07 12:00:00   1st Qu.:2.000
 N.blank  :   0   Median :2012-09-02 00:00:00   Median :3.000
 Min.nchar:   4   Mean   :2012-06-28 14:25:17   Mean   :3.005
 Max.nchar:  12   3rd Qu.:2013-04-19 00:00:00   3rd Qu.:3.000
                  Max.   :2015-01-28 00:00:00   Max.   :9.000
                  NAs    :1027                  NAs    :1039
   Gallop rhythm  Date first detected...15          Arrhythmia
 Length   :1250   Min.   :2007-05-14 23:00:00   Length   :1250
 N.unique :   3   1st Qu.:2012-03-19 00:00:00   N.unique :   3
 N.blank  :   0   Median :2012-12-20 00:00:00   N.blank  :   0
 Min.nchar:   4   Mean   :2012-08-18 07:38:55   Min.nchar:   4
 Max.nchar:  12   3rd Qu.:2013-05-12 00:00:00   Max.nchar:  12
                  Max.   :2014-05-12 00:00:00
                  NAs    :1213
 Date first detected...17            Goitre        Vaccination
 Min.   :2010-10-06 00:00:00   Length   :1250   Length   :1250
 1st Qu.:2012-03-17 12:00:00   N.unique :   3   N.unique :   3
 Median :2012-06-18 12:00:00   N.blank  :   0   N.blank  :   0
 Mean   :2012-10-18 12:00:00   Min.nchar:   4   Min.nchar:   7
 3rd Qu.:2013-06-19 06:00:00   Max.nchar:  12   Max.nchar:  17
 Max.   :2014-09-12 00:00:00
 NAs    :1234
 Previous exposure to nephrotoxic drugs  NSAID treatment
 Length   :1250                         Length   :1250
 N.unique :   3                         N.unique :   3
 N.blank  :   0                         N.blank  :   0
 Min.nchar:   5                         Min.nchar:  17
 Max.nchar:  13                         Max.nchar:  26
                                        NAs      : 739

 Date of last exposure to drug Previous anaesthetic
 Min.   :2002-02-13 00:00:00   Length   :1250
 1st Qu.:2011-03-15 12:00:00   N.unique :   3
 Median :2012-04-16 00:00:00   N.blank  :   0
 Mean   :2011-11-11 07:41:21   Min.nchar:   2
 3rd Qu.:2013-02-12 12:00:00   Max.nchar:  13
 Max.   :2013-12-31 00:00:00
 NAs    :735
 Date of last anaesthetic         FeLV status       FIV status
 Min.   :1997-09-01 00:00:00   Length   :1250   Length   :1250
 1st Qu.:2010-06-28 06:00:00   N.unique :   2   N.unique :   3
 Median :2012-01-23 00:00:00   N.blank  :   0   N.blank  :   0
 Mean   :2011-04-21 16:27:38   Min.nchar:   8   Min.nchar:   8
 3rd Qu.:2012-12-05 18:00:00   Max.nchar:  10   Max.nchar:  10
 Max.   :2013-12-30 00:00:00
 NAs    :868
 Previous exposure to lilies Previous exposure to ethylene glycol
 Length   :1250              Length   :1250
 N.unique :   3              N.unique :   2
 N.blank  :   0              N.blank  :   0
 Min.nchar:   2              Min.nchar:   2
 Max.nchar:  13              Max.nchar:  13


    Previous AKI  Hyperthyroidism Periodontal disease Arthritis
 Length   :1250   Mode :logical   Mode :logical       Mode :logical
 N.unique :   3   FALSE:1127      FALSE:785           FALSE:1139
 N.blank  :   0   TRUE :123       TRUE :465           TRUE :111
 Min.nchar:   2
 Max.nchar:  13


 Cystitis/FLUTD  Cardiomyopathy  Retinopathy     Cat bite abscess
 Mode :logical   Mode :logical   Mode :logical   Mode :logical
 FALSE:1117      FALSE:1207      FALSE:1220      FALSE:1167
 TRUE :133       TRUE :43        TRUE :30        TRUE :83




 Polycystic kidney disease Pyelonephritis  hepatopathy      obesity
 Mode :logical             Mode :logical   Mode :logical   Mode :logical
 FALSE:1247                FALSE:1246      FALSE:1236      FALSE:1206
 TRUE :3                   TRUE :4         TRUE :14        TRUE :44




 constipation    Diabetes Mellitus Primary Aldosteronism Urethral obstruction
 Mode :logical   Mode :logical     Mode :logical         Min.   :0.0000
 FALSE:1228      FALSE:1238        FALSE:1249            1st Qu.:0.0000
 TRUE :22        TRUE :12          TRUE :1               Median :0.0000
                                                         Mean   :0.0112
                                                         3rd Qu.:0.0000
                                                         Max.   :2.0000

In [10]:
table(cat_df$Case)
prop.table(table(cat_df$Case))
#proportion of cases and controls checked

   Case Control
    625     625

   Case Control
    0.5     0.5

In [11]:
install.packages("dplyr")
library(dplyr)
glimpse(cat_df)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Rows: 1,250
Columns: 44
$ ID                                       <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10…
$ Breed                                    <chr> "Crossbreed", "Purebreed", "C…
$ Age                                      <chr> "?9", "?9", "?9", "?9", "?9",…
$ Sex                                      <chr> "Female", "Male", "Male", "Fe…
$ Neuter                                   <chr> "Neutered", NA, "Neutered", "…
$ Case                                     <chr> "Case", "Case", "Case", "Case…
$ `Date of diagnosis`                      <dttm> 2013-02-05, 2012-03-19, 2012…
$ `Reason for presentation`                <chr> "Other", "Not recorded", "Cli…
$ `BCS at diagnosis (1-9)`                 <dbl> NA, NA, NA, NA, NA, NA, NA, N…
$ `Last recorded BCS (1-9)`                <dbl> NA, NA, NA, NA, NA, NA, NA, N…
$ `Heart Murmur`                           <chr> "FALSE", "FALSE", "TRUE", "TR…
$ `HM first recorded`                      <dttm> NA, NA, 2009-10-08, 2010-01-…
$ `Grade of heart murmur`                  <dbl> NA, NA, 5, 3, 1, NA, NA, NA, …
$ `Gallop rhythm`                          <chr> "FALSE", "FALSE", "FALSE", "T…
$ `Date first detected...15`               <dttm> NA, NA, NA, 2010-01-25, 2012…
$ Arrhythmia                               <chr> "FALSE", "FALSE", "FALSE", "F…
$ `Date first detected...17`               <dttm> NA, NA, NA, NA, NA, NA, NA, …
$ Goitre                                   <chr> "Not recorded", "Not recorded…
$ Vaccination                              <chr> "Regular", "None recorded", "…
$ `Previous exposure to nephrotoxic drugs` <chr> "None recorded", "None record…
$ `NSAID treatment`                        <chr> NA, NA, "Repeated one off tre…
$ `Date of last exposure to drug`          <dttm> NA, NA, 2011-05-07, 2013-12-…
$ `Previous anaesthetic`                   <chr> "None recorded", "None record…
$ `Date of last anaesthetic`               <dttm> NA, NA, NA, NA, 2009-12-01, …
$ `FeLV status`                            <chr> "Not tested", "Not tested", "…
$ `FIV status`                             <chr> "Not tested", "Not tested", "…
$ `Previous exposure to lilies`            <chr> "None recorded", "None record…
$ `Previous exposure to ethylene glycol`   <chr> "None recorded", "None record…
$ `Previous AKI`                           <chr> "None recorded", "None record…
$ Hyperthyroidism                          <lgl> TRUE, FALSE, FALSE, FALSE, TR…
$ `Periodontal disease`                    <lgl> FALSE, TRUE, TRUE, TRUE, TRUE…
$ Arthritis                                <lgl> FALSE, FALSE, FALSE, TRUE, FA…
$ `Cystitis/FLUTD`                         <lgl> FALSE, FALSE, TRUE, TRUE, FAL…
$ Cardiomyopathy                           <lgl> FALSE, FALSE, FALSE, TRUE, FA…
$ Retinopathy                              <lgl> FALSE, FALSE, FALSE, FALSE, F…
$ `Cat bite abscess`                       <lgl> FALSE, FALSE, FALSE, FALSE, F…
$ `Polycystic kidney disease`              <lgl> FALSE, FALSE, FALSE, FALSE, F…
$ Pyelonephritis                           <lgl> FALSE, FALSE, FALSE, FALSE, F…
$ hepatopathy                              <lgl> FALSE, FALSE, FALSE, FALSE, F…
$ obesity                                  <lgl> FALSE, FALSE, FALSE, FALSE, F…
$ constipation                             <lgl> FALSE, FALSE, TRUE, FALSE, FA…
$ `Diabetes Mellitus`                      <lgl> FALSE, TRUE, FALSE, FALSE, FA…
$ `Primary Aldosteronism`                  <lgl> FALSE, FALSE, FALSE, FALSE, F…
$ `Urethral obstruction`                   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…

####Association

In [12]:
breed_case_table <- table(cat_df$Breed, cat_df$Case)

In [ ]:
breed_case_table

             Case Control
  Crossbreed  530     553
  Purebreed    87      59
  Unknown       8      13

In [13]:
Age_case_table <- table(cat_df$Age, cat_df$Case)

In [14]:
Age_case_table

     Case Control
  ?9  559     559
  <9   58      58

In [15]:
Periodontal_case_table <- table(cat_df$`Periodontal disease`, cat_df$Case)

In [16]:
Periodontal_case_table

        Case Control
  FALSE  340     445
  TRUE   285     180

In [17]:
druguse_case_table <- table(cat_df$`Previous exposure to nephrotoxic drugs`, cat_df$Case)

In [18]:
druguse_case_table

                Case Control
  Chemotherapy     2       3
  None recorded  388     347
  NSAID          235     275

In [19]:
treatment_case_table <- table(cat_df$`NSAID treatment`, cat_df$Case)

In [20]:
treatment_case_table

                             Case Control
  Long term treatment          43      14
  One-off treatment           142     182
  Repeated one off treatment   51      79

In [21]:
# Convert categorical variables to factors so R can compare
cat_df$Breed <- as.factor(cat_df$Breed)
cat_df$Age <- as.factor(cat_df$Age)
cat_df$Sex <- as.factor(cat_df$Sex)
cat_df$Neuter <- as.factor(cat_df$Neuter)
cat_df$Case <- as.factor(cat_df$Case)

# Convert character TRUE/FALSE columns to logical; converts to actual true/false
cat_df$`Heart Murmur` <- as.logical(cat_df$`Heart Murmur`)
cat_df$`Gallop rhythm` <- as.logical(cat_df$`Gallop rhythm`)
cat_df$Arrhythmia <- as.logical(cat_df$Arrhythmia)

In [22]:
#verify changes worked before modeling so R doesnt error out due to wrong labeling
str(cat_df)

tibble [1,250 × 44] (S3: tbl_df/tbl/data.frame)
 $ ID                                    : num [1:1250] 1 2 3 4 5 6 7 8 9 10 ...
 $ Breed                                 : Factor w/ 3 levels "Crossbreed","Purebreed",..: 1 2 1 1 1 1 1 1 1 1 ...
 $ Age                                   : Factor w/ 2 levels "?9","<9": 1 1 1 1 1 1 1 1 1 2 ...
 $ Sex                                   : Factor w/ 2 levels "Female","Male": 1 2 2 1 2 1 1 2 2 1 ...
 $ Neuter                                : Factor w/ 2 levels "Entire","Neutered": 2 NA 2 2 NA NA 2 2 NA 2 ...
 $ Case                                  : Factor w/ 2 levels "Case","Control": 1 1 1 1 1 1 1 1 1 1 ...
 $ Date of diagnosis                     : POSIXct[1:1250], format: "2013-02-05" "2012-03-19" ...
 $ Reason for presentation               : chr [1:1250] "Other" "Not recorded" "Clinical signs" "Other" ...
 $ BCS at diagnosis (1-9)                : num [1:1250] NA NA NA NA NA NA NA NA NA NA ...
 $ Last recorded BCS (1-9)               : num [1:1250] NA NA NA NA NA NA NA NA NA NA ...
 $ Heart Murmur                          : logi [1:1250] FALSE FALSE TRUE TRUE TRUE FALSE ...
 $ HM first recorded                     : POSIXct[1:1250], format: NA NA ...
 $ Grade of heart murmur                 : num [1:1250] NA NA 5 3 1 NA NA NA NA NA ...
 $ Gallop rhythm                         : logi [1:1250] FALSE FALSE FALSE TRUE TRUE FALSE ...
 $ Date first detected...15              : POSIXct[1:1250], format: NA NA ...
 $ Arrhythmia                            : logi [1:1250] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ Date first detected...17              : POSIXct[1:1250], format: NA NA ...
 $ Goitre                                : chr [1:1250] "Not recorded" "Not recorded" "FALSE" "FALSE" ...
 $ Vaccination                           : chr [1:1250] "Regular" "None recorded" "None recorded" "Regular" ...
 $ Previous exposure to nephrotoxic drugs: chr [1:1250] "None recorded" "None recorded" "NSAID" "NSAID" ...
 $ NSAID treatment                       : chr [1:1250] NA NA "Repeated one off treatment" "Long term treatment" ...
 $ Date of last exposure to drug         : POSIXct[1:1250], format: NA NA ...
 $ Previous anaesthetic                  : chr [1:1250] "None recorded" "None recorded" "None recorded" "None recorded" ...
 $ Date of last anaesthetic              : POSIXct[1:1250], format: NA NA ...
 $ FeLV status                           : chr [1:1250] "Not tested" "Not tested" "Not tested" "Not tested" ...
 $ FIV status                            : chr [1:1250] "Not tested" "Not tested" "Not tested" "Not tested" ...
 $ Previous exposure to lilies           : chr [1:1250] "None recorded" "None recorded" "None recorded" "None recorded" ...
 $ Previous exposure to ethylene glycol  : chr [1:1250] "None recorded" "None recorded" "None recorded" "None recorded" ...
 $ Previous AKI                          : chr [1:1250] "None recorded" "None recorded" "None recorded" "None recorded" ...
 $ Hyperthyroidism                       : logi [1:1250] TRUE FALSE FALSE FALSE TRUE FALSE ...
 $ Periodontal disease                   : logi [1:1250] FALSE TRUE TRUE TRUE TRUE FALSE ...
 $ Arthritis                             : logi [1:1250] FALSE FALSE FALSE TRUE FALSE FALSE ...
 $ Cystitis/FLUTD                        : logi [1:1250] FALSE FALSE TRUE TRUE FALSE FALSE ...
 $ Cardiomyopathy                        : logi [1:1250] FALSE FALSE FALSE TRUE FALSE FALSE ...
 $ Retinopathy                           : logi [1:1250] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ Cat bite abscess                      : logi [1:1250] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ Polycystic kidney disease             : logi [1:1250] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ Pyelonephritis                        : logi [1:1250] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ hepatopathy                           : logi [1:1250] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ obesity                               : logi [1:1250] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ constipation                          : logi [1:1250] FALSE FALSE TRUE FALSE FALSE FALSE ...
 $ Diabetes Mellitus                     : logi [1:1250] FALSE TRUE FALSE FALSE FALSE FALSE ...
 $ Primary Aldosteronism                 : logi [1:1250] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ Urethral obstruction                  : num [1:1250] 0 0 0 0 0 0 0 0 0 0 ...

In [23]:
# Check missing values in chosen covariates only
covariates <- c("Periodontal disease", "Age", "Breed", "Sex",
                "Neuter", "Hyperthyroidism", "NSAID treatment",
                "Previous AKI", "Heart Murmur", "Case")

colSums(is.na(cat_df[covariates]))

Periodontal disease                 Age               Breed                 Sex
                  0                  16                   0                   7
             Neuter     Hyperthyroidism     NSAID treatment        Previous AKI
                349                   0                 739                   0
       Heart Murmur                Case
                515                   0

In [ ]:
#neuter, heart murmur, and NSAID treatment are missing a alot. Safe to assume NA means "NO NSAID treatment"?
#if so, following code changes that
#heart murmur is being dropped from covariate list due to many missing values
#neuter is dropped too

In [25]:
#recoding NA to None for NSAID treatmnet
cat_df$`NSAID treatment`[is.na(cat_df$`NSAID treatment`)] <- "None"
cat_df$`NSAID treatment` <- as.factor(cat_df$`NSAID treatment`)

In [26]:
#checking the values from "previous AKI" bc we dont know what categories it contains
table(cat_df$`Previous AKI`)

           No None recorded           Yes
           86          1154            10

In [ ]:
#drop "previous AKI" bc only 10 out of 1,250 cats had previous AKI

In [27]:
# Fit a logistic regression model to predict CKD (Case/Control)
# Binary outcome (Case) → binomial family with logit link
# All predictors are fixed effects — no clustering variable exists
# na.omit drops rows with missing values in any covariate
model1 <- glm(Case ~ `Periodontal disease` + Age + Breed + Sex +
                Hyperthyroidism + `NSAID treatment`,
              family = binomial(link = "logit"),
              data = cat_df,
              na.action = na.omit)

summary(model1)

Call:
glm(formula = Case ~ `Periodontal disease` + Age + Breed + Sex +
    Hyperthyroidism + `NSAID treatment`, family = binomial(link = "logit"),
    data = cat_df, na.action = na.omit)

Coefficients:
                                            Estimate Std. Error z value
(Intercept)                                  -0.2456     0.3376  -0.728
`Periodontal disease`TRUE                    -0.9106     0.1341  -6.788
Age<9                                        -0.4258     0.2090  -2.037
BreedPurebreed                               -0.4606     0.1890  -2.437
BreedUnknown                                  0.4131     0.5005   0.825
SexMale                                      -0.0987     0.1244  -0.793
HyperthyroidismTRUE                          -2.7033     0.3425  -7.892
`NSAID treatment`None                         0.6905     0.3392   2.036
`NSAID treatment`One-off treatment            1.2813     0.3517   3.643
`NSAID treatment`Repeated one off treatment   1.5666     0.3836   4.084
                                            Pr(>|z|)
(Intercept)                                 0.466877
`Periodontal disease`TRUE                   1.14e-11 ***
Age<9                                       0.041643 *
BreedPurebreed                              0.014808 *
BreedUnknown                                0.409141
SexMale                                     0.427688
HyperthyroidismTRUE                         2.97e-15 ***
`NSAID treatment`None                       0.041789 *
`NSAID treatment`One-off treatment          0.000269 ***
`NSAID treatment`Repeated one off treatment 4.42e-05 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1702.4  on 1227  degrees of freedom
Residual deviance: 1511.2  on 1218  degrees of freedom
  (22 observations deleted due to missingness)
AIC: 1531.2

Number of Fisher Scoring iterations: 5

In [ ]:
#check significance